import Foundation

// Dev-cache reclaim - the pure half. Mirrors claude-code/reclaim-contract.js
// and the GNOME extension's lib/pure/reclaim.js 1:1; tests/fixtures is not
// needed here because the catalog IS the contract and ReclaimTests asserts it
// against the same list the JS tests do. Foundation only, so it unit-tests on
// Linux CI.
//
// This is the one feature in this repo that deletes things, so it is built the
// other way round from everything else: the catalog is a fixed, reviewable
// list of exact paths (never a glob, never a walk looking for things that look
// deletable), every entry says what it is and what losing it costs, nothing
// happens without an explicit choice, and what does happen is a move to the
// trash - recoverable by Finder's own Put Back - never an unlink.
//
// Two kinds of entry, and the difference is the whole point:
//   cache / logs - regenerated by the tool that wrote them. Safe.
//   history      - your own work: transcripts you can still resume, and the
//                  only local record of what your plan was spent on. Never
//                  offered by default; a caller has to ask for it by name.

public struct ReclaimEntry: Equatable, Sendable, Identifiable {
    public enum Kind: String, Sendable {
        case cache, logs, history
    }

    public let id: String
    public let tool: String
    public let label: String
    public let kind: Kind
    public let note: String
    public let path: String
    /// Bytes on disk; nil until it has been measured, and after measuring when
    /// the path is not there at all.
    public var bytes: Int?

    public var exists: Bool { bytes != nil }
    public var human: String { Reclaim.formatBytes(bytes ?? 0) }

    public init(
        id: String, tool: String, label: String, kind: Kind, note: String, path: String,
        bytes: Int? = nil
    ) {
        self.id = id
        self.tool = tool
        self.label = label
        self.kind = kind
        self.note = note
        self.path = path
        self.bytes = bytes
    }
}

/// What a reclaim run would do (see `Reclaim.plan`).
public struct ReclaimPlan: Equatable, Sendable {
    public enum Refusal: String, Sendable {
        case unknown, history, empty
    }

    public let targets: [ReclaimEntry]
    public let totalBytes: Int
    public let refused: [(id: String, why: Refusal)]

    public init(targets: [ReclaimEntry], totalBytes: Int, refused: [(id: String, why: Refusal)]) {
        self.targets = targets
        self.totalBytes = totalBytes
        self.refused = refused
    }

    public static func == (a: ReclaimPlan, b: ReclaimPlan) -> Bool {
        a.targets == b.targets && a.totalBytes == b.totalBytes
            && a.refused.map(\.id) == b.refused.map(\.id)
            && a.refused.map(\.why) == b.refused.map(\.why)
    }
}

public enum Reclaim {
    /// The directories the catalog is written in terms of.
    public struct Dirs: Sendable {
        public let home: String
        public let claudeHome: String
        public let codexHome: String
        public let xdgCache: String
        public let xdgConfig: String

        public init(
            home: String, claudeHome: String, codexHome: String, xdgCache: String,
            xdgConfig: String
        ) {
            self.home = home
            self.claudeHome = claudeHome
            self.codexHome = codexHome
            self.xdgCache = xdgCache
            self.xdgConfig = xdgConfig
        }
    }

    private struct Spec {
        let id: String
        let tool: String
        let label: String
        let kind: ReclaimEntry.Kind
        let note: String
        /// Path template per platform; "all" when it is the same everywhere.
        let paths: [String: String]
    }

    private static let catalog: [Spec] = [
        Spec(
            id: "claude-shell-snapshots", tool: "Claude Code", label: "Shell snapshots",
            kind: .cache,
            note:
                "One captured shell environment per session. Claude Code writes a new one when it needs it.",
            paths: ["all": "{claudeHome}/shell-snapshots"]),
        Spec(
            id: "claude-statsig", tool: "Claude Code", label: "Feature-flag cache", kind: .cache,
            note: "Cached feature flags. Refetched on the next run.",
            paths: ["all": "{claudeHome}/statsig"]),
        Spec(
            id: "claude-todos", tool: "Claude Code", label: "Per-session todo lists", kind: .cache,
            note: "The todo list of each past session. A resumed session rebuilds its own.",
            paths: ["all": "{claudeHome}/todos"]),
        Spec(
            id: "claude-downloads", tool: "Claude Code", label: "Downloaded installers",
            kind: .cache, note: "Update payloads Claude Code already installed.",
            paths: ["all": "{claudeHome}/downloads"]),
        Spec(
            id: "claude-projects", tool: "Claude Code", label: "Session transcripts",
            kind: .history,
            note:
                "Every past conversation, and what `claude --resume` resumes. Also what this panel "
                + "reads to rank today's sessions. Not a cache.",
            paths: ["all": "{claudeHome}/projects"]),
        Spec(
            id: "panel-session-index", tool: "Claude usage panel", label: "Session index",
            kind: .cache,
            note: "This panel's incremental fold of the transcripts. Rebuilt on the next poll.",
            paths: [
                "darwin": "{home}/Library/Caches/claude-usage-panel",
                "linux": "{xdgCache}/claude-usage-panel",
            ]),
        Spec(
            id: "cursor-cache", tool: "Cursor", label: "Editor caches", kind: .cache,
            note: "HTTP and resource cache. Rebuilt as you work.",
            paths: [
                "darwin": "{home}/Library/Application Support/Cursor/Cache",
                "linux": "{xdgConfig}/Cursor/Cache",
            ]),
        Spec(
            id: "cursor-cached-data", tool: "Cursor", label: "Compiled extension data",
            kind: .cache,
            note: "Per-version compiled sources. Rebuilt on the next launch, which is slower once.",
            paths: [
                "darwin": "{home}/Library/Application Support/Cursor/CachedData",
                "linux": "{xdgConfig}/Cursor/CachedData",
            ]),
        Spec(
            id: "cursor-code-cache", tool: "Cursor", label: "Code cache", kind: .cache,
            note: "V8 code cache. Rebuilt on the next launch.",
            paths: [
                "darwin": "{home}/Library/Application Support/Cursor/Code Cache",
                "linux": "{xdgConfig}/Cursor/Code Cache",
            ]),
        Spec(
            id: "cursor-gpu-cache", tool: "Cursor", label: "GPU cache", kind: .cache,
            note: "Shader cache. Rebuilt on the next launch.",
            paths: [
                "darwin": "{home}/Library/Application Support/Cursor/GPUCache",
                "linux": "{xdgConfig}/Cursor/GPUCache",
            ]),
        Spec(
            id: "cursor-logs", tool: "Cursor", label: "Logs", kind: .logs,
            note: "One directory per window session. Only useful while reporting a bug.",
            paths: [
                "darwin": "{home}/Library/Application Support/Cursor/logs",
                "linux": "{xdgConfig}/Cursor/logs",
            ]),
        Spec(
            id: "codex-logs", tool: "OpenAI Codex", label: "Logs", kind: .logs,
            note: "The codex CLI's own log files.", paths: ["all": "{codexHome}/log"]),
        Spec(
            id: "codex-sessions", tool: "OpenAI Codex", label: "Session transcripts",
            kind: .history,
            note:
                "Every past Codex conversation, and the only local record of the rate limits the "
                + "API reported. Clearing it makes `claudectl codex usage` blind. Not a cache.",
            paths: ["all": "{codexHome}/sessions"]),
    ]

    /// Every id the catalog knows, in catalog order.
    public static var ids: [String] { catalog.map(\.id) }

    /// The entries offered when the user has not named any: the regenerated
    /// ones, never their own history.
    public static var defaultIds: [String] {
        catalog.filter { $0.kind != .history }.map(\.id)
    }

    /// The catalog for one platform, with every `{placeholder}` expanded.
    public static func entries(dirs: Dirs, platform: String = "darwin") -> [ReclaimEntry] {
        let values = [
            "home": dirs.home, "claudeHome": dirs.claudeHome, "codexHome": dirs.codexHome,
            "xdgCache": dirs.xdgCache, "xdgConfig": dirs.xdgConfig,
        ]
        return catalog.compactMap { spec in
            guard let template = spec.paths[platform] ?? spec.paths["all"] else { return nil }
            var path = template
            for (key, value) in values {
                path = path.replacingOccurrences(of: "{\(key)}", with: value)
            }
            return ReclaimEntry(
                id: spec.id, tool: spec.tool, label: spec.label, kind: spec.kind, note: spec.note,
                path: path)
        }
    }

    /// What a reclaim run would do. Nothing is decided anywhere else: a caller
    /// hands in the scanned entries and the ids the user chose, and gets back
    /// exactly what to move, what to leave, and why. `ids == nil` means "the
    /// regenerated ones"; `includeHistory` is the caller saying out loud that
    /// it named a history entry and meant it.
    public static func plan(
        scanned: [ReclaimEntry], ids: [String]? = nil, includeHistory: Bool = false
    ) -> ReclaimPlan {
        var byId: [String: ReclaimEntry] = [:]
        for entry in scanned { byId[entry.id] = entry }
        var targets: [ReclaimEntry] = []
        var refused: [(id: String, why: ReclaimPlan.Refusal)] = []
        for id in ids ?? defaultIds {
            guard let entry = byId[id] else {
                refused.append((id, .unknown))
                continue
            }
            // A history entry is never swept up by a default run, and never
            // moved by a named one either unless the caller meant it.
            if entry.kind == .history && !includeHistory {
                refused.append((id, .history))
                continue
            }
            guard let bytes = entry.bytes, bytes > 0 else {
                refused.append((id, .empty))
                continue
            }
            targets.append(entry)
        }
        return ReclaimPlan(
            targets: targets, totalBytes: targets.reduce(0) { $0 + ($1.bytes ?? 0) },
            refused: refused)
    }

    private static let units = ["B", "KB", "MB", "GB", "TB"]

    /// "1.4 GB" - one decimal from KB up, whole bytes below. Identical in
    /// every port so a dry run and the log that follows it never disagree.
    public static func formatBytes(_ bytes: Int?) -> String {
        guard let bytes, bytes >= 0 else { return "-" }
        if bytes < 1024 { return "\(bytes) B" }
        var value = Double(bytes)
        var unit = 0
        while value >= 1024 && unit < units.count - 1 {
            value /= 1024
            unit += 1
        }
        return String(format: "%.1f %@", value, units[unit])
    }
}
