#!/usr/bin/env bash
# The file-size ceiling: no text file in the repo is over 700 lines. When one
# gets close, it is split by concern (that is how install.sh became
# scripts/install/*.sh and pure.js a barrel), not waved through.
#
# Two outcomes only. A file is under the ceiling, or it is DECLARED below by
# name with the reason it may grow. There is no numeric slack and no advisory
# tier. A declared entry that no longer matches any tracked file over the
# ceiling fails too: an exemption that outlived its reason is deleted, not kept.
#
#   scripts/check-file-size.sh          check the repo this script lives in
#
# Runs in pre-commit (every commit) and therefore in CI's lint job.
set -euo pipefail

MAX_LINES=700

# Entry format: PATTERN|REASON. PATTERN is a shell glob matched against the
# repo-relative path. Keep each one as narrow as the reason allows.
EXEMPT=(
    "CHANGELOG.md|append-only release history; every release adds a section"
    "claude-usage-panel@fschmutz.github.io/po/*.po|generated by scripts/update-po.sh; one entry per UI string in every language"
    "claude-usage-panel@fschmutz.github.io/po/*.pot|generated by scripts/update-po.sh; the template every .po merges from"
)

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

exempt_reason() { # PATH -> prints the reason, returns 1 when not exempt
    local entry pattern
    for entry in "${EXEMPT[@]}"; do
        pattern="${entry%%|*}"
        # shellcheck disable=SC2254  # the pattern is a glob on purpose
        case "$1" in
            $pattern)
                printf '%s\n' "${entry#*|}"
                return 0
                ;;
        esac
    done
    return 1
}

fail=0
used=""
# Tracked and new (not ignored) files; binaries are skipped by grep -I. The
# list is taken first so a failing git fails the gate instead of feeding the
# loop nothing (a process substitution would swallow that exit status).
files="$(git ls-files --cached --others --exclude-standard)"
while IFS= read -r f; do
    [ -f "$f" ] || continue
    grep -Iq '' "$f" 2>/dev/null || continue
    n=$(wc -l <"$f" | tr -d ' ')
    [ "$n" -gt "$MAX_LINES" ] || continue
    if reason="$(exempt_reason "$f")"; then
        echo "  - $f: $n lines, declared: $reason"
        used="$used
$f"
    else
        echo "  x $f: $n lines, over the $MAX_LINES-line ceiling - split it by concern" >&2
        fail=1
    fi
done <<<"$files"

for entry in "${EXEMPT[@]}"; do
    pattern="${entry%%|*}"
    hit=0
    while IFS= read -r f; do
        [ -n "$f" ] || continue
        # shellcheck disable=SC2254  # the pattern is a glob on purpose
        case "$f" in $pattern) hit=1 ;; esac
    done <<<"$used"
    if [ "$hit" -eq 0 ]; then
        echo "  x exemption '$pattern' matches no file over $MAX_LINES lines - delete the entry" >&2
        fail=1
    fi
done

if [ "$fail" -ne 0 ]; then
    echo "check-file-size: failed (ceiling $MAX_LINES lines, exemptions are named in scripts/check-file-size.sh)" >&2
    exit 1
fi
echo "check-file-size: every file is within $MAX_LINES lines or declared"
