// The "hit the limit → switch → room left" storyboard (docs/switch-story.svg),
// the one beat a static dropdown screenshot cannot tell. Three frames of the
// same top bar and the same two account rows, drawn from the REAL shared logic
// - panelText, usageReading, formatAccountUsage, nextInRotation - so the
// picture cannot claim something the code does not do. render.mjs owns the
// palette, the clock and the drift gate; this module only returns the SVG.

import {
  formatAccountUsage, nextInRotation, panelText, usageReading,
} from '../../claude-usage-panel@fschmutz.github.io/lib/pure.js';

const W = 900;
const FRAME_W = 276;
const FRAME_H = 196;
const GAP = 36;
const TOP = 96;

/**
 * @param {object} deps
 * @param {object} deps.C the palette render.mjs uses
 * @param {string} deps.FONT the font attribute
 * @param {(s: string) => string} deps.esc
 * @param {object} deps.story the `switchStory` block of data.json
 */
export function storySvg({C, FONT, esc, story}) {
  const parts = [];
  const text = (x, y, s, size, fill, extra = '') =>
    parts.push(`<text x="${x}" y="${y}" font-size="${size}" fill="${fill}" ${FONT} ${extra}>${esc(s)}</text>`);

  text(36, 46, '✳ Hit the limit, switch, keep going', 24, C.text, 'font-weight="800"');
  text(36, 74, story.subtitle, 14, C.dim);

  story.frames.forEach((frame, i) => {
    const x = 36 + i * (FRAME_W + GAP);
    parts.push(
      `<rect x="${x}" y="${TOP}" width="${FRAME_W}" height="${FRAME_H}" rx="14" ` +
      `fill="${C.card}" stroke="${C.cardBorder}"/>`);
    text(x + 16, TOP + 26, `${i + 1}. ${frame.title}`, 13, C.text, 'font-weight="700"');

    // The top bar, exactly as panelText would build it: the account name only
    // when it fits beside the reading, and the em dash when there is no
    // honest percentage to show (usageReading).
    const worst = frame.cards.reduce((a, b) => (b.percent > a.percent ? b : a));
    const reading = usageReading({...worst, percentKnown: worst.percentKnown !== false});
    const bar = panelText({
      account: frame.active, label: worst.label, percent: worst.percent, known: reading.known,
    });
    const sev = reading.known && worst.percent >= 100 ? C.critical
      : reading.known && worst.percent >= 90 ? C.warning : C.accent;
    parts.push(
      `<rect x="${x + 16}" y="${TOP + 38}" width="${FRAME_W - 32}" height="30" rx="8" ` +
      `fill="${C.bg}" stroke="${C.cardBorder}"/>`);
    parts.push(`<circle cx="${x + 32}" cy="${TOP + 53}" r="5" fill="${sev}"/>`);
    text(x + 44, TOP + 58, bar, 13, C.text, 'font-weight="600"');

    // The two account rows the dropdown shows, with the same "S 42% · W 12%"
    // summary formatAccountUsage produces.
    let rowY = TOP + 92;
    for (const account of frame.accounts) {
      const active = account.name === frame.active;
      const cards = [
        {key: 'session', percent: account.session},
        {key: 'weekly_all', percent: account.weekly},
      ];
      const full = Math.max(account.session, account.weekly) >= 100;
      text(x + 16, rowY, `${active ? '●' : '○'} ${account.name}`, 12, active ? C.text : C.dim,
        `font-weight="${active ? 700 : 600}"`);
      text(x + FRAME_W - 16, rowY, formatAccountUsage(cards), 12,
        full ? C.critical : C.dim, 'text-anchor="end"');
      rowY += 24;
    }

    // The quiet line the accounts section carries once there is a rotation.
    const next = nextInRotation(frame.accounts.map((a) => a.name), frame.active);
    text(x + 16, TOP + FRAME_H - 38, frame.note, 11, C.dim);
    if (next) text(x + 16, TOP + FRAME_H - 20, `Next: ${next}`, 11, C.accent);

    if (i < story.frames.length - 1) {
      const arrowX = x + FRAME_W + GAP / 2;
      text(arrowX, TOP + FRAME_H / 2 + 6, '→', 22, C.dim, 'text-anchor="middle"');
    }
  });

  const H = TOP + FRAME_H + 56;
  text(36, H - 22, story.footer, 12, C.dim);

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/screenshots/render.mjs - edit data.json, not this file. -->
<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
<rect width="${W}" height="${H}" rx="16" fill="${C.bg}"/>
${parts.join('\n')}
</svg>
`;
}
